### ISSUE TITLE
SSL Key is missing from setup

### ISSUE THREAD

**Issue by tomjrtsmith** [berndhofer/freqstart#72]
? Which IP to access FreqUI:
  1) Public IP (WAN)
  2) Local IP (LAN)
  Choose number: 1
  Continue with: https://xxx.x.xxx.xxx

+ Run project: freqstart_nginx.yml
  Image is installed: amd64/nginx:stable
Creating freqstart_nginx_freqstart_nginx_ip_run ... done
exec /docker-entrypoint.sh: exec format error
ERROR: 1

! [ERROR] SSL key does not exist. Restart Nginx setup!

**Comment by berndhofer** [comment]
Please re-download the develop branch and see if there are any OS/architecture warnings occurring at the start of the script.

**Comment by tomjrtsmith** [comment]
I re-ran after running git checkout develop and got the response

> [WARNING] No valid public IP (v4) found!

This is on an amd 64 ubuntu vps

**Comment by berndhofer** [comment]
@tomjrtsmith The public ip validation should work now as intended.

**Comment by tomjrtsmith** [comment]
Public IP validation works for IP addresses

I fixed up my DNS config and selecting option 1 returns

> 

! [WARNING] The domain "xxx.xxxxxx.xx" does not point to "xxx.xx.xxx.xxx". Review DNS and try again!

I think this might be problematic on most vps provider firewalls as they don't allow ping. 

After installing SSL the script returned this error which looks like an apache conflict

> 

+ Container: freqstart_nginx_ip
? Update container automatically (recommended)? (y/n) y
  Image is up-to-date: amd64/nginx:stable
Error response from daemon: driver failed programming external connectivity on endpoint freqstart_nginx_ip (ea610dd6ebe02f4ace5103eb85c18518b237dbba12aa2ddea0d7531dffd6d771): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp4 0.0.0.0:80: bind: address already in use
Error: failed to start containers: freqstart_nginx_ip

+ Validate project: freqstart_nginx.yml
! [WARNING] Container is not active: freqstart_nginx_ip

! [ERROR] Nginx container is not running. Restart Nginx setup!

**Comment by tomjrtsmith** [comment]
DNS config works with domain selection, disregard 1st error. I hadn't updated one of the a records properly. 

Still fails on port 80 error which I'll leave to be fixed with the script rather than messing with the apache conf files myself.

**Comment by berndhofer** [comment]
IP validation fixed in v2.0.7; moving the other request in a new issue.
